name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *" # a cada 12 horas, no minuto 0
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest
    steps:
      # Gera a animação Snake
      - uses: Platane/snk/svg-only@v3
        id: snake-gif
        with:
          github_user_name: cherry-leeh
          outputs: dist/github-contribution-grid-snake.svg

      # Publica no branch 'output'
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
